Add vercel deploy link as starter options
sanity-io/community-studio pull request #92
Opened 2022-09-16 10:20 UTC by RitaDias

Hi 👋 

This is a very small step towards a bigger initiative to add different deploy options within the exchange. Right now, the studio only uses the sanity jumpstart logic, with the changes in this PR we've added an option to use the vercel deployment links. 

Here is the expected behavior:

https://user-images.githubusercontent.com/6951139/190617310-21c09cf5-10ef-44e3-8f95-9237613593eb.mov

(not in this pr, but for illustration of the "end" of the flow)

https://user-images.githubusercontent.com/6951139/190617433-5ff7fb10-741a-4271-a6cb-8458edf4b141.mov

2022-09-16 14:35 UTC, sjelfull requested changes

2022-09-16 14:35 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +          {title: 'sanity deploy', value: 'github'},
```suggestion
          {title: 'Jumpstart', value: 'jumpstart'},
```

2022-09-16 14:35 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +      initialValue: 'github',
```suggestion
      initialValue: 'jumpstart',
```

2022-09-16 14:35 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +      hidden: ({parent}) => parent.deploymentType !== 'github',
```suggestion
      hidden: ({parent}) => parent.deploymentType !== 'jumpstart',
```

2022-09-16 14:35 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +          return context.parent.deploymentType === 'github'
```suggestion
          return context.parent.deploymentType === 'jumpstart'
```

2022-09-16 14:36 UTC, sjelfull commented
General question: Can we keep `repoId` regardless of deployment type?

I see multiple uses for it in the future, like a link on the details page and possibly other autogenerated links.

2022-09-16 14:36 UTC, sjelfull commented
Added suggestions for updating the naming/casing of things

2022-09-19 11:05 UTC, RitaDias commented
> General question: Can we keep `repoId` regardless of deployment type?
> 
> I see multiple uses for it in the future, like a link on the details page and possibly other autogenerated links.

We can! The question I have is more on how do we want to handle the validation?
Because right now I check if the vercel option is picked. Should it be then that if it has the Vercel Deploy option picked that it doesn't have the .required() or any other validation?

(I also will add that while I think it could be useful, I think we're probably going to want to make changes in that as well in the future)

2022-09-19 12:11 UTC, RitaDias commented
@sjelfull I've updated it here and on the website itself (https://github.com/sanity-io/www-sanity-io/pull/1007) to this:
- `RepoId` always exists on the studio doc
- Repo Id validation only appears if the option for "vercel deployment" isn't picked
- If a user picks vercel deployment (regardless if the repoid field is filled or not), the website will give priority to the vercel deployment link

2022-09-23 11:51 UTC, sjelfull commented on schemas/components/Preview.js
> +  switch (displayed.jumpstartStartType) {
```suggestion
  switch (displayed.deploymentType) {
```

2022-09-23 11:57 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +      title: 'Vercel deploy link',
```suggestion
      title: 'Vercel Deploy Button link',
```

2022-09-23 12:27 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +      description: 'The Vercel deployment link generated from the deploy button',
```suggestion
      description: 'The generated Vercel Deploy Button link',
```

2022-09-23 12:27 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +            ? 'You must have a vercel deploy link'
```suggestion
            ? 'You must have a Vercel Deploy Button link'
```

2022-09-23 12:31 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +          We currently offer two options to deploy your starter: using sanity.io/create and vercel!
```suggestion
          We currently offer two options to deploy your starter: using sanity.io/create and Vercel!
```

2022-09-23 12:35 UTC, sjelfull commented on schemas/documents/contributions/starter.js
> +        'Using the sanity.io/create means that we will generate a deployment page based on the provided repo id. If Vercel is picked, then you will need to generate a deployment url based on their de
```suggestion
        'Using the sanity.io/create means that we will generate a deployment page based on the provided repo id. If Vercel is picked, then you will need to generate a Deploy Button link.',
```

2022-09-23 12:40 UTC, sjelfull approved these changes

2022-09-26 08:00 UTC, merged