Added template
sanity-io/community-studio pull request #97
Opened 2022-11-02 08:41 UTC by ninaandal

2022-11-15 09:12 UTC, RitaDias requested changes
<img width="640" alt="image" src="https://user-images.githubusercontent.com/6951139/201877679-8d3340eb-ad37-4329-94dc-1b6689c08147.png">

To double check, we decided to go with cssFrameworks being mandatory? @mariuslundgard

<img width="326" alt="image" src="https://user-images.githubusercontent.com/6951139/201877961-dda53b3a-a9f7-4825-8ccd-7d10fc9fd151.png">

Maybe a nitpick but should we update the validation messages at least for those fields since they are bit more tech-y than they probably need to?

2022-11-15 09:12 UTC, RitaDias commented
Also makes me wonder what do we want to do with the previews? I assume that we didn't end up doing anything with them but I'm guess that they will be wrong for the v3 templates? @mariuslundgard do you have any thoughts?

2022-11-15 09:13 UTC, RitaDias commented
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/6951139/201878683-7dc0942d-e4d1-4cd9-86e0-504880266cdc.png">

If I switch from v3 (after having added a title and seen the validation errors) -> v2 templates the validation errors from v3 are still appearing on the validation tab

2022-11-16 09:02 UTC, ninaandal commented
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/6951139/201877679-8d3340eb-ad37-4329-94dc-1b6689c08147.png">
> 
> To double check, we decided to go with cssFrameworks being mandatory? @mariuslundgard
> 
> <img alt="image" width="326" src="https://user-images.githubusercontent.com/6951139/201877961-dda53b3a-a9f7-4825-8ccd-7d10fc9fd151.png">
> 
> Maybe a nitpick but should we update the validation messages at least for those fields since they are bit more tech-y than they probably need to?

No, this is not nitpick - thanks for pointing this out! I have fixed this 👍 

About the CSS Framework - yes, but we will include an "Other" option if it is not applicable

2022-11-16 09:05 UTC, ninaandal commented
> Also makes me wonder what do we want to do with the previews? I assume that we didn't end up doing anything with them but I'm guess that they will be wrong for the v3 templates? @mariuslundgard do you have any thoughts?

Won't we be able to show the sanity page you are making as an `iframe`?

2022-11-16 09:17 UTC, RitaDias commented
> 
> Won't we be able to show the sanity page you are making as an `iframe`?

That is the plan yes! I might have missed it but I don't think any code about the preview was charged in this PR right? Which I'm assuming that then it won't work out of the box for v3 or maybe I missed something?

2022-11-16 09:24 UTC, RitaDias commented
<img width="992" alt="image" src="https://user-images.githubusercontent.com/6951139/202140344-c9913d80-eb2b-430d-a9fe-a6dcee3a2ebc.png">

still getting a v3 error when I go from v3 -> v2 (relative address in the community website field)
Actually, the field appearing for v2 overall is an error, isn't it? I think that field shouldn't be appearing in v2 🤔 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/6951139/202140837-700912ae-3fcb-4a58-a051-e107497911a1.png">

Also, it looks like there are some file conflicts 👇

2022-11-16 09:26 UTC, RitaDias commented on schemas/documents/contributions/starter.js
> +          {value: -1, title: 'n/a'},
While looking at this I was wondering if it wouldn't make sense to also add the deprecated to the field directly. What do you think @mariuslundgard 
```suggestion
          {value: 2, title: 'Studio v2 (deprecated)'},
          {value: -1, title: 'n/a (deprecated)'},
```

2022-11-16 09:27 UTC, ninaandal commented
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/6951139/202140344-c9913d80-eb2b-430d-a9fe-a6dcee3a2ebc.png">
> 
> still getting a v3 error when I go from v3 -> v2 (relative address in the community website field) Actually, the field appearing for v2 overall is an error, isn't it? I think that field shouldn't be appearing in v2 🤔
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/6951139/202140837-700912ae-3fcb-4a58-a051-e107497911a1.png">
> 
> Also, it looks like there are some file conflicts 👇

But this is the `slug` field, which I thought was mandatory for both v2 and v3?

2022-11-16 09:29 UTC, ninaandal commented
> > Won't we be able to show the sanity page you are making as an `iframe`?
> 
> That is the plan yes! I might have missed it but I don't think any code about the preview was charged in this PR right? Which I'm assuming that then it won't work out of the box for v3 or maybe I missed something?

No, I haven't done anything with the previews yet, as you weren't done with the page yet! Mind if we do it in a separate PR after this is merged?

2022-11-16 09:49 UTC, RitaDias commented
> > > Won't we be able to show the sanity page you are making as an `iframe`?
> > 
> > 
> > That is the plan yes! I might have missed it but I don't think any code about the preview was charged in this PR right? Which I'm assuming that then it won't work out of the box for v3 or maybe I missed something?
> 
> No, I haven't done anything with the previews yet, as you weren't done with the page yet! Mind if we do it in a separate PR after this is merged?

Just so you all know, we've spoken and a new task was created to update the preview / make sure the preview works for the new v3

2022-11-16 11:18 UTC, RitaDias approved these changes
✅ let's go!

2022-11-16 11:50 UTC, RitaDias commented on schemas/documents/contributions/starter.js
> +        hidden: ({parent}) => parent.studioVersion === 3,
```suggestion
        hidden: ({parent}) => parent.studioVersion !== 3,
```

2022-11-16 12:23 UTC, merged